#!/bin/sh
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mdev -s
clear
cat <<'EOF'
.-.-----------.-.
| |-ZPLinux---|#|
| |-v0.2------| |
| |-For-486DX-| |
| |-with-<3---| |
| "-----------' |
|  .-----.-..   |
|  |     | || |||
|  |     | || \/|
"--^-----^-^^---'
Original ASCII art by Edward Farrow (asciiart.eu).
Author: Matteo Pacini <m+github@matteopacini.me>.
Repository: https://github.com/Zi0P4tch0/ZPLinux.
EOF
sleep 3
setsid cttyhack sh
