name: build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean Bloat
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'rampage'
          witness-carnage: true

      - uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: zplinux-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: zplinux-

      - name: Build 
        run: |
          nix build path:.#zplinuxFloppyA

      - name: Upload floppy image artifact
        uses: actions/upload-artifact@v4
        with:
          name: zplinux-floppy-a
          path: ./result/zplinux-floppy-a.img
