name: build

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  ATTIC_CACHE_NAME: ${{ secrets.ATTIC_CACHE_NAME }}
  ATTIC_CACHE_URL: ${{ secrets.ATTIC_CACHE_URL }}
  ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean GH Runners Bloat
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'rampage'
          witness-carnage: true
          nix-permission-edict: true

      - uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Configure Attic cache
        run: |
          nix run nixpkgs#attic-client -- login \
            "${{ env.ATTIC_CACHE_NAME }}" "${{ env.ATTIC_CACHE_URL }}" "${{ env.ATTIC_TOKEN }}"
          nix run nixpkgs#attic-client -- use zplinux

      - name: Build 
        run: |
          nix build path:.#zplinuxFloppyA

      - uses: nick-fields/retry@v3
        name: Push to nix cache
        with:
          timeout_minutes: 7200
          max_attempts: 5
          retry_on: error
          command: nix run nixpkgs#attic-client -- push zplinux ./result -j 3

      - name: Upload floppy image artifact
        uses: actions/upload-artifact@v4
        with:
          name: zplinux-floppy-a
          path: ./result/zplinux-floppy-a.img
